"""Data contracts and schemas for the Aegis Scanner engine."""

from dataclasses import dataclass, field
from typing import Callable, Any

# Callback signatures for progress reporting and cancellation checks
ProgressCallback = Callable[[str, int, str, str], None]  # (stage, percent, message, level)
CancelCheck = Callable[[], bool]


@dataclass
class AccountConfig:
    """Configuration for an account to crawl and replay under."""
    label: str                      # e.g. "admin", "alice", "bob"
    privilege_level: int            # higher = more privileged (e.g. 1..100)
    login_url: str
    username: str
    password: str                   # Plaintext in memory only during active scan
    username_selector: str
    password_selector: str
    submit_selector: str
    dismiss_selectors: list[str] = field(default_factory=list)
    success_url_contains: str | None = None
    identifiers: list[str] = field(default_factory=list)


@dataclass
class ScanConfig:
    """Execution options for an access control scan."""
    base_url: str
    scope_hosts: list[str]
    accounts: list[AccountConfig]
    max_pages: int = 30
    max_depth: int = 3
    request_delay_ms: int = 200
    max_replays: int = 500
    seed_paths: list[str] = field(default_factory=list)
    allow_private: bool = False
    modules: list[str] = field(default_factory=lambda: ["access_control"])


@dataclass
class RecordedRequest:
    """Network request and response captured during browser recording."""
    account_label: str
    method: str
    url: str
    headers: dict[str, str]
    body: str | None
    resource_type: str              # "document" | "xhr" | "fetch" | "script"
    status: int
    response_headers: dict[str, str]
    response_body: str | None       # text only, capped at 200 KB when recorded
    content_type: str | None
    signature: str                  # from signature.py


@dataclass
class ReplayResult:
    """Outcome of a single replayed HTTP request."""
    status: int
    headers: dict[str, str]
    body: str                       # capped at 2 MB, decoded with errors="replace"
    error: str | None = None


@dataclass
class FindingResult:
    """Access control flaw or security finding generated by the scanner."""
    type: str
    title: str
    severity: str
    confidence: int
    cvss_score: float
    cvss_vector: str
    cwe: str
    owasp: str
    method: str
    url: str
    signature: str
    source_role: str
    tested_role: str
    description: str
    remediation: str
    evidence: dict


@dataclass
class ScanResult:
    """Aggregate result from an access control scan run."""
    endpoints: list[RecordedRequest]     # metadata only is persisted by backend
    findings: list[FindingResult]
    stats: dict                          # requests_recorded, replays_sent, discarded_low_confidence
